version: 2.1

orbs:
  architect: giantswarm/architect@0.11.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-event-exporter-app-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "event-exporter-app"
          context: "architect"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-event-exporter-app-to-aws-app-collection
          app_name: "event-exporter-app"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          filters:
            # Do not trigger the job on commit.
            branches:
              ignore: /.*/
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
