version: 2.1

orbs:
  architect: giantswarm/architect@5.11.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          chart: event-exporter-app
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-aws-app-collection
          context: architect
          app_name: event-exporter-app
          app_collection_repo: aws-app-collection
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-azure-app-collection
          context: architect
          app_name: event-exporter-app
          app_collection_repo: azure-app-collection
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capa-app-collection
          context: architect
          app_name: event-exporter-app
          app_collection_repo: capa-app-collection
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capz-app-collection
          context: architect
          app_name: event-exporter-app
          app_collection_repo: capz-app-collection
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
