version: 2.1

orbs:
  architect: giantswarm/architect@6.2.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          executor: app-build-suite
          chart: event-exporter-app
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          persist_chart_archive: true
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capa-app-collection
          context: architect
          app_name: event-exporter-app
          app_collection_repo: capa-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capz-app-collection
          context: architect
          app_name: event-exporter-app
          app_collection_repo: capz-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
