apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "event-exporter.fullname" . }}
  labels: {{ include "event-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machinedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.giantswarm.io
  resources:
  - awsclusters
  - awscontrolplanes
  - awsmachinedeployments
  - g8scontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
