apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "event-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "event-exporter.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{ include "event-exporter.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "event-exporter.fullname" . }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: event-exporter
        image: {{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.securityContext }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        args:
        - --conf
        - /data/config.yaml
        volumeMounts:
        - name: config
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: {{ include "event-exporter.fullname" . }}
