kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.networkPolicy.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    app: event-exporter-app
spec:
  podSelector:
    matchLabels:
      app: event-exporter-app
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
