apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "event-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "event-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "event-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
