{{- if .Capabilities.APIVersions.Has "kyverno.io/v2beta1/PolicyException" -}}
{{- if .Capabilities.APIVersions.Has "kyverno.io/v2/PolicyException" -}}
apiVersion: kyverno.io/v2
{{- else }}
apiVersion: kyverno.io/v2beta1
{{- end }}
kind: PolicyException
metadata:
  name: {{ .Values.name }}-exceptions
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: require-run-as-nonroot 
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ .Values.name }}*
