apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-exporter-app
rules:
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
      - machinedeployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - infrastructure.giantswarm.io
    resources:
      - awsclusters
      - awsmachinedeployments
      - awscontrolplanes
      - g8scontrolplanes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
    - events
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - replicasets
    - deployments
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - argoproj.io
    resources:
    - applications
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
{{- if and (le (int .Capabilities.KubeVersion.Minor) 24) (not .Values.global.podSecurityStandards.enforced) }}
  - apiGroups:
    - extensions
    resourceNames:
    - {{ .Values.name }}-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-exporter-app
subjects:
  - kind: ServiceAccount
    name: event-exporter-app
    namespace: {{ .Release.Namespace }}
