{{- if .Values.verticalPodAutoscaler.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "event-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "event-exporter.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ include "event-exporter.fullname" . }}
  resourcePolicy:
    containerPolicies:
    - containerName: event-exporter
      controlledValues: RequestsAndLimits
      mode: Auto
  updatePolicy:
    updateMode: Auto
{{- end }}
